# Generated by Django 3.0.7 on 2022-06-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_notices'),
    ]

    operations = [
        migrations.AddField(
            model_name='notices',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
