# Generated by Django 3.0.7 on 2022-06-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_notices_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notices',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
